export const TYPE_META : Record<string, { color: string; emoji: string }> = {
  all:      { color: '#888780', emoji: '🔘' },
  fire:     { color: '#E84343', emoji: '🔥' },
  water:    { color: '#378add', emoji: '🌊' },
  grass:    { color: '#639922', emoji: '🌿' },
  electric: { color: '#EF9F27', emoji: '⚡' },
  psychic:  { color: '#D4537E', emoji: '🔮' },
  ice:      { color: '#85B7EB', emoji: '❄️' },
  dragon:   { color: '#534AB7', emoji: '🐉' },
  dark:     { color: '#444441', emoji: '🌑' },
  fairy:    { color: '#ED93B1', emoji: '🧚🏻‍♀️' },
  normal:   { color: '#B4B2A9', emoji: '⚪' },
  fighting: { color: '#993C1D', emoji: '🥊' },
  flying:   { color: '#AFA9EC', emoji: '🕊️' },
  poison:   { color: '#7F77DD', emoji: '☠️' },
  ground:   { color: '#BA7517', emoji: '🌍' },
  rock:     { color: '#888780', emoji: '🪨' },
  bug:      { color: '#3B6D11', emoji: '🐛' },
  ghost:    { color: '#3C3489', emoji: '👻' },
  steel:    { color: '#5F5E5A', emoji: '⚙️' },
  stellar:   { color: '#FFD700', emoji: '🌟' },
  unknown:   { color: '#888780', emoji: '❓' },
}